completion-plugins:
  - name: openai
    source: https://github.com/bradyjoslin/assembllm-openai/releases/latest/download/assembllm_openai.wasm
    hash: 
    apiKey: OPENAI_API_KEY
    url: api.openai.com
    model: 
  - name: perplexity
    source: https://github.com/bradyjoslin/assembllm-perplexity/releases/latest/download/assembllm_perplexity.wasm
    hash: 
    apiKey: PERPLEXITY_API_KEY
    url: api.perplexity.ai
    model: 
  - name: cloudflare
    source: https://github.com/bradyjoslin/assembllm-cloudflare/releases/latest/download/assembllm_cloudflare.wasm
    hash: 
    apiKey: WORKERS_AI_TOKEN
    accountId: CF_ACCOUNT_ID
    url: api.cloudflare.com
    model: 
  - name: anthropic
    source: https://github.com/bradyjoslin/assembllm-anthropic-go/releases/latest/download/assembllm-anthropic-go.wasm
    hash: 
    apiKey: ANTHROPIC_API_KEY
    url: api.anthropic.com
    model: 
    wasi: true
