completion-plugins:
  - name: openai
    source: ./plugins/openai_completions_rust.wasm
    hash: 114e1e892c43baefb4d50cc8b0e9f66df2b2e3177de9293ffdd83898c77e04c7
    apiKey: OPENAI_API_KEY
    url: api.openai.com
    model: 4o
  - name: perplexity
    source: ./plugins/perplexity_completions_rust.wasm
    hash: 9c1a87483040d5033866fc5b8581cc8aa7bc18abd9a601a14a4dec998a5a75f9
    apiKey: PERPLEXITY_API_KEY
    url: api.perplexity.ai
    model: llam3-sso
  - name: openaigo
    source: ./plugins/openai_completions_go.wasm
    hash: 0e127b2f3cdffeaa440a7d900156887416799efb0a7e88ed6862dbe379fd8143
    apiKey: OPENAI_API_KEY
    url: api.openai.com
    model: gpt-4o
    wasi: true
  - name: openaicsharp
    source: ./plugins/openai_completions_csharp.wasm
    hash: 6d2e458bf3eea4925503bc7803c0d01366430a8e2779bd088b8f9887745b4e00
    apiKey: OPENAI_API_KEY
    url: api.openai.com
    model: gpt-4o
    wasi: true
